stages:
  - test
  - build

test:
  stage: test
  image:
    name: $CI_REGISTRY_IMAGE:latest
    entrypoint: [""]
  script:
    - pip install -e ".[all]"
    - trial -j 4 tests

build:
  stage: build
  image: docker:latest
  services:
  - docker:dind
  variables:
    DOCKER_BUILDKIT: 1
  before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
  - if [ $CI_COMMIT_BRANCH == "master" ]; then tag=$(cat synapse/__init__.py | grep '__version__ = "' | sed -E 's/^__version__ = "(.+)"$/\1/'); fi
  - if [ $CI_COMMIT_BRANCH != "master" ]; then tag=$CI_COMMIT_SHA; fi
  - docker build --tag $CI_REGISTRY_IMAGE:$tag -f docker/Dockerfile .
  - docker push $CI_REGISTRY_IMAGE:$tag
